apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pomerium-mcp-markdown

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: mcp-markdown
  version: v1.0.0
