name: Pre-commit
permissions:
  contents: read
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: make install

      - name: Run pre-commit
        run: make pre-commit
